UPLOAD_ERRORS_TRANSLATIONS = {
    "NotFoundError": "Requisição não encontrada (404). Verifique o endpoint ou o recurso solicitado.",
    "BadRequestError": "Requisição inválida (400). Verifique os dados enviados.",
    "AuthenticationFailure": "Falha na autenticação (401). Verifique sua chave ou token de acesso.",
    "TooManyRequestsError": "Muitas requisições em pouco tempo (429). Tente novamente mais tarde.",
    "FewMemory": "Limite de memória atingido. Aumente sua alocação de memória.",
    "BadMemory": "Valor de memória inválido no arquivo de configuração.",
    "MissingConfigFile": "Arquivo de configuração ausente no .zip (squarecloud.app/squarecloud.config).",
    "MissingDependenciesFile": "Arquivo de dependências ausente (requirements.txt, package.json, etc).",
    "MissingMainFile": "Arquivo principal ausente (main.py, index.js, etc).",
    "InvalidMain": "O campo MAIN no config está inválido ou o arquivo principal está corrompido.",
    "InvalidDisplayName": "O campo DISPLAY_NAME no config está inválido.",
    "MissingDisplayName": "O campo DISPLAY_NAME está ausente no config.",
    "InvalidMemory": "O campo MEMORY no config é inválido.",
    "MissingMemory": "O campo MEMORY está ausente no config.",
    "InvalidVersion": 'O campo VERSION é inválido. Os valores aceitos são "recommended" ou "latest".',
    "MissingVersion": "O campo VERSION está ausente no config.",
    "InvalidAccessToken": "Token de acesso do GitHub inválido.",
    "InvalidDomain": "Domínio fornecido inválido.",
    "InvalidFile": "O arquivo enviado não é um arquivo válido (.zip)",
}
